# Display Private Key Upload Guide
# Quick reference for uploading private keys in Django admin

Clear-Host

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║          HOW TO UPLOAD PRIVATE KEY IN DJANGO ADMIN                  ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Write-Host "STEP 1: Access Django Admin" -ForegroundColor Yellow
Write-Host "────────────────────────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "  URL: " -NoNewline -ForegroundColor White
Write-Host "http://localhost:8001/admin/" -ForegroundColor Green
Write-Host "  Login with your admin credentials" -ForegroundColor White
Write-Host ""

Write-Host "STEP 2: Navigate to Organizations" -ForegroundColor Yellow
Write-Host "────────────────────────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "  Click: " -NoNewline -ForegroundColor White
Write-Host '"Organizations"' -NoNewline -ForegroundColor Green
Write-Host " in the left menu" -ForegroundColor White
Write-Host "  Click: Your organization name (e.g., " -NoNewline -ForegroundColor White
Write-Host '"P1"' -NoNewline -ForegroundColor Green
Write-Host " or " -NoNewline -ForegroundColor White
Write-Host '"P2"' -NoNewline -ForegroundColor Green
Write-Host ")" -ForegroundColor White
Write-Host ""

Write-Host "STEP 3: Upload Private Key" -ForegroundColor Yellow
Write-Host "────────────────────────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host ""
Write-Host "  ┌──────────────────────────────────────────────────────────────┐" -ForegroundColor Gray
Write-Host "  │  Add private key                                             │" -ForegroundColor Gray
Write-Host "  ├──────────────────────────────────────────────────────────────┤" -ForegroundColor Gray
Write-Host "  │                                                              │" -ForegroundColor Gray
Write-Host "  │  Key file:  [Choose File]  No file chosen                   │" -ForegroundColor Gray
Write-Host "  │                                                              │" -ForegroundColor Gray
Write-Host "  │  Private Key Password: [                    ]               │" -ForegroundColor Gray
Write-Host "  │                         " -NoNewline -ForegroundColor Gray
Write-Host "↑" -ForegroundColor Red
Write-Host "  │                         " -NoNewline -ForegroundColor Gray
Write-Host "└─ LEAVE THIS EMPTY!" -ForegroundColor Red
Write-Host "  │                                                              │" -ForegroundColor Gray
Write-Host "  │  [Save]                                                      │" -ForegroundColor Gray
Write-Host "  └──────────────────────────────────────────────────────────────┘" -ForegroundColor Gray
Write-Host ""
Write-Host "  1. Click " -NoNewline -ForegroundColor White
Write-Host "[Choose File]" -ForegroundColor Green
Write-Host "  2. Select: " -NoNewline -ForegroundColor White
Write-Host "P1_private.pem" -NoNewline -ForegroundColor Green
Write-Host " (for P1) or " -NoNewline -ForegroundColor White
Write-Host "P2_private.pem" -NoNewline -ForegroundColor Green
Write-Host " (for P2)" -ForegroundColor White
Write-Host "  3. " -NoNewline -ForegroundColor White
Write-Host "⚠️  IMPORTANT: " -NoNewline -ForegroundColor Red
Write-Host "Leave " -NoNewline -ForegroundColor White
Write-Host '"Private Key Password"' -NoNewline -ForegroundColor Yellow
Write-Host " field " -NoNewline -ForegroundColor White
Write-Host "EMPTY" -ForegroundColor Red
Write-Host "  4. Click " -NoNewline -ForegroundColor White
Write-Host "[Save]" -ForegroundColor Green
Write-Host ""

Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Red
Write-Host "║                           CRITICAL NOTES                             ║" -ForegroundColor Red
Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Red
Write-Host ""
Write-Host "  ⚠️  DO NOT enter any password in the " -NoNewline -ForegroundColor Yellow
Write-Host '"Private Key Password"' -NoNewline -ForegroundColor White
Write-Host " field" -ForegroundColor Yellow
Write-Host ""
Write-Host "  ⚠️  The keys generated by " -NoNewline -ForegroundColor Yellow
Write-Host "generate_certificates.py" -NoNewline -ForegroundColor White
Write-Host " are NOT encrypted" -ForegroundColor Yellow
Write-Host ""
Write-Host "  ⚠️  Leaving the password field empty is " -NoNewline -ForegroundColor Yellow
Write-Host "CORRECT" -NoNewline -ForegroundColor Green
Write-Host " behavior" -ForegroundColor Yellow
Write-Host ""

Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║                         COMMON MISTAKES                              ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  ❌ Entering " -NoNewline -ForegroundColor Red
Write-Host '"password"' -NoNewline -ForegroundColor White
Write-Host " or " -NoNewline -ForegroundColor Red
Write-Host '"admin"' -NoNewline -ForegroundColor White
Write-Host " in the password field" -ForegroundColor Red
Write-Host "  ❌ Entering any text in the password field" -ForegroundColor Red
Write-Host "  ❌ Using " -NoNewline -ForegroundColor Red
Write-Host "P1_public.pem" -NoNewline -ForegroundColor White
Write-Host " instead of " -NoNewline -ForegroundColor Red
Write-Host "P1_private.pem" -ForegroundColor White
Write-Host "  ❌ Using separate .key and .crt files" -ForegroundColor Red
Write-Host ""

Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                         CORRECT APPROACH                             ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  ✅ Use " -NoNewline -ForegroundColor Green
Write-Host "P1_private.pem" -NoNewline -ForegroundColor White
Write-Host " (for P1) or " -NoNewline -ForegroundColor Green
Write-Host "P2_private.pem" -NoNewline -ForegroundColor White
Write-Host " (for P2)" -ForegroundColor Green
Write-Host "  ✅ Leave password field completely " -NoNewline -ForegroundColor Green
Write-Host "EMPTY" -ForegroundColor Yellow
Write-Host "  ✅ Click Save" -ForegroundColor Green
Write-Host "  ✅ Done!" -ForegroundColor Green
Write-Host ""

Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Yellow
Write-Host "║                         IF YOU GET AN ERROR                          ║" -ForegroundColor Yellow
Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Error: " -NoNewline -ForegroundColor White
Write-Host '"Invalid Private Key or password is not correct"' -ForegroundColor Red
Write-Host ""
Write-Host "  Solution:" -ForegroundColor Yellow
Write-Host "  1. Clear the password field (make sure it's completely empty)" -ForegroundColor White
Write-Host "  2. Try uploading again" -ForegroundColor White
Write-Host "  3. If still failing, regenerate certificates:" -ForegroundColor White
Write-Host "     " -NoNewline
Write-Host "python generate_certificates.py" -ForegroundColor Cyan
Write-Host "  4. See " -NoNewline -ForegroundColor White
Write-Host "PRIVATE_KEY_TROUBLESHOOTING.md" -NoNewline -ForegroundColor Cyan
Write-Host " for detailed help" -ForegroundColor White
Write-Host ""

Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "║                         NEED MORE HELP?                              ║" -ForegroundColor Magenta
Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Magenta
Write-Host ""
Write-Host "  See: " -NoNewline -ForegroundColor White
Write-Host "PRIVATE_KEY_TROUBLESHOOTING.md" -ForegroundColor Cyan
Write-Host "  Run: " -NoNewline -ForegroundColor White
Write-Host "python fix_private_key_format.py" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Or check the logs:" -ForegroundColor White
Write-Host "  " -NoNewline
Write-Host "docker-compose logs p1 -f" -ForegroundColor Cyan
Write-Host ""

Write-Host "Press any key to exit..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
